export const data = [
  {
    name: 'Zone 1',
    price: 9,
    zones: [
      { zipcode: '97230', city: 'Portland', dir: 'NE' },
      { zipcode: '97220', city: 'Portland', dir: 'NE' },
      { zipcode: '97213', city: 'Portland', dir: 'NE' },
      { zipcode: '97212', city: 'Portland', dir: 'NE' },
      { zipcode: '97218', city: 'Portland', dir: 'NE' },
      { zipcode: '97211', city: 'Portland', dir: 'NE' },
      { zipcode: '97217', city: 'Portland', dir: 'N' },
      { zipcode: '97203', city: 'Portland', dir: 'N' },
      { zipcode: '98660', city: 'Vancouver', dir: false },
      { zipcode: '98665', city: 'Vancouver', dir: false },
      { zipcode: '98683', city: 'Vancouver', dir: false },
      { zipcode: '98664', city: 'Vancouver', dir: false },
      { zipcode: '98663', city: 'Vancouver', dir: false },
      { zipcode: '98661', city: 'Vancouver', dir: false },
      { zipcode: '98684', city: 'Vancouver', dir: false },
      { zipcode: '98682', city: 'Vancouver', dir: false },
      { zipcode: '98662', city: 'Vancouver', dir: false },
      { zipcode: '98685', city: 'Vancouver', dir: false },
      { zipcode: '98686', city: 'Vancouver', dir: false },
      { zipcode: '97232', city: 'Portland', dir: 'NE' },
      { zipcode: '97227', city: 'Portland', dir: 'N' }
    ]
  },
  {
    name: 'Zone 2',
    price: 10,
    zones: [
      { zipcode: '98604', city: 'Battle Ground', dir: false },
      { zipcode: '98606', city: 'Brush Prairie', dir: 'NE' },
      { zipcode: '98607', city: 'Brush Prairie', dir: 'NE' },
      { zipcode: '97060', city: 'Wood Village', dir: false },
      { zipcode: '97024', city: 'Fairview', dir: 'NE' },
      { zipcode: '97030', city: 'Gresham', dir: false },
      { zipcode: '97233', city: 'Portland', dir: 'SE' },
      { zipcode: '97236', city: 'Portland', dir: 'SE' },
      { zipcode: '97086', city: 'Happy Valley', dir: 'SE' },
      { zipcode: '97015', city: 'Clackamas', dir: 'SE' },
      { zipcode: '97267', city: 'Milwaukie', dir: 'SE' },
      { zipcode: '97222', city: 'Milwaukie', dir: 'SE' },
      { zipcode: '97266', city: 'Portland', dir: 'SE' },
      { zipcode: '97206', city: 'Portland', dir: 'SE' },
      { zipcode: '97216', city: 'Portland', dir: 'SE' },
      { zipcode: '97215', city: 'Portland', dir: 'SE' },
      { zipcode: '97202', city: 'Portland', dir: 'SE' },
      { zipcode: '97214', city: 'Portland', dir: 'SE' },
      { zipcode: '97034', city: 'Lake Oswego', dir: false },
      { zipcode: '97035', city: 'Lake Oswego', dir: false },
      { zipcode: '97219', city: 'Portland', dir: 'SW' },
      { zipcode: '97239', city: 'Portland', dir: 'SW' },
      { zipcode: '97201', city: 'Portland', dir: 'SW' },
      { zipcode: '97204', city: 'Portland', dir: 'SW' },
      { zipcode: '97209', city: 'Portland', dir: 'NW' },
      { zipcode: '97210', city: 'Portland', dir: 'NW' },
      { zipcode: '97205', city: 'Portland', dir: 'SW' },
      { zipcode: '97221', city: 'Portland', dir: 'SW' },
      { zipcode: '97225', city: 'Portland', dir: 'SW' },
      { zipcode: '97229', city: 'Portland', dir: 'NW' },
      { zipcode: '97005', city: 'Beaverton', dir: 'SW' }
    ]
  },
  {
    name: 'Zone 3',
    price: 11,
    zones: [
      { zipcode: '98674', city: 'Woodland', dir: false },
      { zipcode: '98629', city: 'La Center', dir: false },
      { zipcode: '98607', city: 'Yacolt', dir: false },
      { zipcode: '98675', city: 'Yacolt', dir: false },
      { zipcode: '98671', city: 'Washougal', dir: false },
      { zipcode: '97019', city: 'Corbett', dir: false },
      { zipcode: '97009', city: 'Boring', dir: false },
      { zipcode: '97089', city: 'Damascus', dir: false },
      { zipcode: '97045', city: 'Oregon City', dir: false },
      { zipcode: '97027', city: 'Gladstone', dir: false },
      { zipcode: '97068', city: 'West Linn', dir: false },
      { zipcode: '97062', city: 'Tualatin', dir: false },
      { zipcode: '97224', city: 'Tigard', dir: false },
      { zipcode: '97223', city: 'Tigard', dir: false },
      { zipcode: '97008', city: 'Beaverton', dir: false },
      { zipcode: '97007', city: 'Beaverton', dir: false },
      { zipcode: '97078', city: 'Aloha', dir: false },
      { zipcode: '97003', city: 'Hillsboro', dir: false },
      { zipcode: '97006', city: 'Hillsboro', dir: false },
      { zipcode: '97124', city: 'Hillsboro', dir: false },
      { zipcode: '97231', city: 'Portland', dir: 'NW' }
    ]
  },
  {
    name: 'Zone 4',
    price: 12,
    zones: [
      { zipcode: '98626', city: 'Kelso', dir: false },
      { zipcode: '98625', city: 'Kalama', dir: false },
      { zipcode: '98603', city: 'Ariel', dir: false },
      { zipcode: '98601', city: 'Amboy', dir: false },
      { zipcode: '98610', city: 'Carson', dir: false },
      { zipcode: '98648', city: 'Stevenson', dir: false },
      { zipcode: '97014', city: 'Cascade Locks', dir: false },
      { zipcode: '97049', city: 'Zigzag', dir: false },
      { zipcode: '97055', city: 'Sandy', dir: false },
      { zipcode: '97067', city: 'Welches', dir: false },
      { zipcode: '97022', city: 'Eagle Creek', dir: false },
      { zipcode: '97023', city: 'Estacada', dir: false },
      { zipcode: '97004', city: 'Beavercreek', dir: false },
      { zipcode: '97042', city: 'Mulino', dir: false },
      { zipcode: '97013', city: 'Canby', dir: false },
      { zipcode: '97002', city: 'Aurora', dir: false },
      { zipcode: '97070', city: 'Wilsonville', dir: false },
      { zipcode: '97140', city: 'Sherwood', dir: false },
      { zipcode: '97123', city: 'Hillsboro', dir: false },
      { zipcode: '97113', city: 'Cornelius', dir: false },
      { zipcode: '97116', city: 'Glenwood', dir: false },
      { zipcode: '97106', city: 'Banks', dir: false },
      { zipcode: '97133', city: 'North Plains', dir: false },
      { zipcode: '97056', city: 'Scappose', dir: false },
      { zipcode: '97053', city: 'Warren', dir: false },
      { zipcode: '97051', city: 'Saint Helens', dir: false },
      { zipcode: '97054', city: 'Deer Island', dir: false },
      { zipcode: '97048', city: 'Prescott', dir: false },
      // { zipcode: '98625', city: 'Kalama', dir: false },
      // { zipcode: '98626', city: 'Kelso', dir: false }
    ]
  }
];
